image:
  file: .gitpod.Dockerfile

tasks:
  - init: mvn clean install -Pjar -DskipTests
    command: cp zeebe-sink.properties ~/confluent-5.5.0/etc/kafka-connect-zeebe-sink && /home/gitpod/confluent-5.5.0/bin/confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:latest && /home/gitpod/confluent-5.5.0/bin/confluent local start

ports:
  - port: 8083
